### PR TITLE
Update XpandNavigationItem.cs

### PR DESCRIPTION
**Pull request by neo-james**
Changed "XpandNavigationItemAttribute" to add caption.
Changed "XpandNavigationItem2NodeUpdater" to 
 * Make it simpler to read
 * Implement the caption change

### CODE REVIEW

**Comment by neo-james** [comment]
Comments removed

**Comment by neo-james** [comment]
I changed the "XpandNavigationItemAttribute" to add caption property.

**Comment by neo-james** [comment]
Then changed "XpandNavigationItem2NodeUpdater"

removed method "AddNodes" which is recursive and complex  with simple one with simple foreach method "GetParentNavigationItems"

also removed method "GetNavigationItem"  with method "AddNavigationItem"

**Comment by neo-james** [comment]
I suggest you to not compare the code, Rather read my code alone to see the new idea

**Comment by apobekiaris** [comment]
for future reference the new idea should be the commit message and not the refactoring u did. For example `XpandNavigationItemAttribute support for Caption`

I will cleanup this request manually for now but I will retain your authorship. Thanks for the time sending the request, feel free to send more. see  also https://github.com/eXpandFramework/eXpand/issues/260

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.21](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=275&view=results) includes commit ["XpandNavigationItemAttribute support for Caption #260 #258"](https://github.com/eXpandFramework/lab/commit/1670f3b35d5f5259e350afb9c55db6591f0d9043) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
Installer lab build [18.2.301.67](https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=475&view=results) includes commit ["XpandNavigationItemAttribute support for Caption #260 #258"](https://github.com/eXpandFramework/lab/commit/a0605f0af72342431911c829dc22fe4a5f3d42b7) that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS

**Comment by apobekiaris** [comment]
include in 18.2.302

**Pull request closed without merging**
