### PR TITLE
Update ChangeVersion.ps1

### PR DESCRIPTION
**Pull request by dsikic**
Is this double X correct? Seems to break my build process.

### CODE REVIEW

**Comment by apobekiaris** [comment]
actually it is correct 

https://github.com/eXpandFramework/eXpand/blob/f916916dcf045b5317c48a8d7740fdc169f86fe4/Support/Build/Install-Module.ps1#L11

note the prefix switch, it was made this way to avoid conflict with existing XpandPwsh installation as its build is bound to a specific version for compatibility. What error do u get?

**Comment by dsikic** [comment]
See here. I'm going to compare behavior with a clean version of Expand. 

`Executing Clean
Executing Init
Remove directories
Copying 3rd party assemlies
Update Code Analysis
Update Projects
Executing Version
InvokeScript : 
Message                     : A parameter cannot be found that matches parameter name 'Top'.
ParameterName               : Top
ParameterType               : 
TypeSpecified               : 
ErrorId                     : NamedParameterNotFound
Line                        : 23
Offset                      : 35
CommandInvocation           : System.Management.Automation.InvocationInfo
ErrorRecord                 : A parameter cannot be found that matches parameter name 'Top'.
WasThrownFromThrowStatement : True
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : 
TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext, System.Exception)
StackTrace                  :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                                 at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                                 at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                                 at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
                                 at System.Management.Automation.CommandProcessorBase.Complete()
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087
At C:\Users\user\Projects\eXpand\support\build\Build.ps1:84 char:5
+     InvokeScript{
+     ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,InvokeScript
 
InvokeScript : 
**MyCommand             : Get-XXXpandVersion**
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 8
OffsetInLine          : 15
HistoryId             : 1
ScriptName            : C:\Users\user\Projects\eXpand\support\build\changeversion.ps1
Line                  : $xpandVersion=Get-XXpandVersion -XpandPath $XpandFolder 
                        
PositionMessage       : At C:\Users\user\Projects\eXpand\support\build\changeversion.ps1:8 char:15
                        + $xpandVersion=Get-XXpandVersion -XpandPath $XpandFolder
                        +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PSScriptRoot          : C:\Users\user\Projects\eXpand\support\build
PSCommandPath         : C:\Users\user\Projects\eXpand\support\build\changeversion.ps1
**InvocationName        : Get-XXpandVersion**
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition : 
At C:\Users\user\Projects\eXpand\support\build\Build.ps1:84 char:5
+     InvokeScript{
+     ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,InvokeScript
 

`

**Comment by apobekiaris** [comment]
i can for sure see 3 XXX thats not correct your commit fixes the XX

**Comment by dsikic** [comment]
Even with my change I have other build issues, but much further down the line. 

`Services\ExternalToolsService.cs(24,42): warning VSTHRD010: Accessing "Events" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\user\Projects\eXpand\Xpand.Plugins\Xpand.VSIX\Xpand.VSIX.csproj]
Services\ExternalToolsService.cs(26,39): warning VSTHRD010: Accessing "Events" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\user\Projects\eXpand\Xpand.Plugins\Xpand.VSIX\Xpand.VSIX.csproj]
Services\ExternalToolsService.cs(28,42): warning VSTHRD010: Accessing "Events" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\user\Projects\eXpand\Xpand.Plugins\Xpand.VSIX\Xpand.VSIX.csproj]
Services\ExternalToolsService.cs(31,62): warning VSTHRD010: Accessing "Events" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\user\Projects\eXpand\Xpand.Plugins\Xpand.VSIX\Xpand.VSIX.csproj]
Services\ExternalToolsService.cs(107,94): warning VSTHRD010: Accessing "_Solution" should only be done on the main thread. Call System.Windows.Threading.Dispatcher.VerifyAccess() first. [C:\Users\user\Projects\eXpand\Xpand.Plugins\Xpand.VSIX\Xpand.VSIX.csproj]
ModelEditor\GridHelper.cs(125,18): warning VSTHRD110: Observe the awaitable result of this method call by awaiting it, assigning to a variable, or passing it to another method. [C:\Users\user\Projects\eXpand\Xpand.Plugins\Xpand.VSIX\Xpand.VSIX.csproj]
  Xpand.VSIX -> C:\Users\user\Projects\eXpand\Xpand.Dll\Plugins\Xpand.VSIX.dll
  Xpand.VSIX -> C:\Users\user\Projects\eXpand\Xpand.Dll\Plugins\Xpand.VSIX.vsix
Executing IndexSources
Error: 10/8/2019 11:47:31 AM: 
At C:\Users\user\Projects\eXpand\support\build\Build.ps1:90 char:10 +     $sha=Get-GitLastSha "https://github.com/eXpandFramework/$reposito ... +          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: A positional parameter cannot be found that 
accepts argument '$null'.
`

**Comment by apobekiaris** [comment]
these are just warnings what is the problem with them? the build does not fail for them they belong to the VSIX

**Comment by apobekiaris** [comment]
>A positional parameter cannot be found that accepts argument '$null'.

positional parameter refers to a parameter based on position without the parameter name so given ln90

``ps1
$sha=Get-GitLastSha "https://github.com/eXpandFramework/$repository" $branch
```
safe guess the $branch is null check what happen before. I would suggest to use VsCode and the powershell plugin. Then u can set breakpoint and step in the code pretty match like VS

**Comment by dsikic** [comment]
You're right the build does complete but it doesn't print durations like normal so I wanted to fix it. I'm also having issues with Fasterflect failing on EditModelController. This is what prompted me to pull your latest changes. Seeing as you migrated Fasterflect to NuGet package references.

That's off topic though.

I'm stepping into a meeting, back in a couple of hours. 

This class is a copy(and descendent) of Xpand's and has worked for years. Now it fails, meanwhile the base class works in the Video Rental demo. So I'm trying to see what's wrong with my approach.

`public class **EditModelController : Xpand.ExpressApp.Win.EditModelController**
    {
        public EditModelController()
        {
            TargetWindowType = WindowType.Main;
        }

        protected override void EditModel()
        {
            SecuritySystem.ReloadPermissions();
            **typeof(DevExpress.ExpressApp.Win.SystemModule.EditModelController).Invoke(this, "UpdateActivity");**
            if (SecuritySystem.Instance is IRequestSecurity)
                SecuritySystem.Demand(new ModelOperationPermissionRequest());
            else
                SecuritySystem.Demand(new EditModelPermission(ModelAccessModifier.Allow));
            EditModelCore();
        }`

`No match for method with name UpdateActivity and flags Instance | NonPublic | Public | Static on type ....Module.Win.Controllers.EditModelController with parameter count 0 and types: .

   at Fasterflect.Emitter.LookupUtils.GetMethod(CallInfo callInfo)
   at Fasterflect.Emitter.MethodInvocationEmitter.CreateDelegate()
   at Fasterflect.Emitter.BaseEmitter.GetDelegate()
   at Fasterflect.MethodExtensions.DelegateForCallMethod(Type type, Type[] genericTypes, String name, Flags bindingFlags, Type[] parameterTypes)
   at Fasterflect.MethodExtensions.CallMethod(Object obj, String name, Object[] parameters)
   at ....Module.Win.Controllers.EditModelController.EditModel() in C:\Users\user\Projects\P\...\....Module.Win\Controllers\EditModelController.cs:line 25
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)`

**Comment by apobekiaris** [comment]
please open an isssue and not here and provide a sample with repro directions and happy to help u fix it

**Pull request closed without merging**
