### PR TITLE
FrameExtensions.GetControllers compatible with custom implementations

### PR DESCRIPTION
**Pull request by gerritmulder**
See issue https://github.com/eXpandFramework/eXpand/issues/444

### CODE REVIEW

**Comment by apobekiaris** [comment]
note that pull requests on this branch do not trigger the pipeline universe.


To make a release u need to have a lab release first. so send a PR to https://github.com/eXpandFramework/eXpand.lab so to create a release there https://github.com/eXpandFramework/eXpand.lab/releases. 

Note the authorship of the work remains to u and it will propagate once the lab repo is integrated

**Comment by apobekiaris** [comment]
either way this work has to be done so this pull request can remain here open until i merge it myself

**Comment by gerritmulder** [comment]
So no need for a PR in the lab repo?

**Comment by apobekiaris** [comment]
yeah fill free to explore the pipeline universe if u like https://dev.azure.com/eXpandDevOps.

**Comment by apobekiaris** [comment]
included in 17.1.303.8

**Pull request closed without merging**
